### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by kapricreations** [huberflores/NQueensCodeOffloading#1]
how to run in cloud? The application is running fine locally, I need help for the "Run in cloud" button, please help me out with the procedure. What is the cloud here and how to connect the NQueens app with the cloud?
thank you.

**Comment by huberflores** [comment]
You need a server with the Android compiler, similar to the one which is shown here https://github.com/huberflores/BenchmarkingAndroidx86. Along with the Nqueens demo, we also provide the server, but you need your own Amazon account to access it.

**Comment by kapricreations** [comment]
Sir, I now have my own Amazon account can you please guide me with the process to access and execute the Nqueens demo.

**Comment by huberflores** [comment]
I sent the information of the instance to your e-mail :)

**Comment by kapricreations** [comment]
Thank you so much sir, i am highly obliged :)
